### ISSUE TITLE
Error running gulp

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/map#6]
I imagine this is something simple, right?
```
[testbed@testbed2 map]$ npm install
[testbed@testbed2 map]$ gulp
[17:27:29] Using gulpfile ~/map/gulpfile.js
[17:27:29] Starting 'lint'...
[17:27:29] Starting 'build-css'...
[17:27:29] Starting 'merge-groups'...
[17:27:29] Starting 'prepare-terriajs'...
[17:27:29] Finished 'lint' after 61 ms
[17:27:29] Finished 'build-css' after 262 ms
[17:27:29] Finished 'merge-groups' after 275 ms
[17:27:29] Starting 'merge-catalog'...
[17:27:29] Finished 'merge-catalog' after 24 ms
[17:27:29] Starting 'merge-datasources'...
[17:27:29] Finished 'merge-datasources' after 8.45 μs
[17:27:30] Finished 'prepare-terriajs' after 669 ms
[17:27:30] Starting 'build-app'...
[17:27:30] Starting 'build-specs'...
[17:27:30] Finished 'build-specs' after 194 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module './log' from '/home/testbed/map/node_modules/terriajs/node_modules/html2canvas/dist'
    at /home/testbed/map/node_modules/browserify/node_modules/resolve/lib/async.js:55:21
    at load (/home/testbed/map/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/testbed/map/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /home/testbed/map/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)
```

**Comment by kring** [comment]
Unfortunately the latest version of html2canvas is broken.  We've changed NationalMap and TerriaJS to use the older, working version, but haven't merged that here yet.

**Comment by rsignell-usgs** [comment]
@kring, this has been fixed, I believe, correct?

**Comment by kring** [comment]
Yes, I believe so.
